Add backend tests (user endpoint)
team-ebi/spacehop pull request #179
Opened 2020-10-17 13:38 UTC by noritaketakamichi

2020-10-17 13:39 UTC, noritaketakamichi commented
post(api/users/account) should  be changed to get method?????

2020-10-18 05:00 UTC, yusuke99 commented
> post(api/users/account) should be changed to get method?????

@noritaketakamichi Get request don't have body so it's post. Or we can change it to params and make it a get request.

2020-10-18 13:43 UTC, noritaketakamichi commented
フロントもこれで作ってるみたいだからこのままでいいや！

2020-10-19 01:58 UTC, yusuke99 requested changes
@noritaketakamichi コメント書いたよ🙏

2020-10-19 01:58 UTC, yusuke99 commented on server/test/migrationsForTest/20201012165159_sample_08.js
@noritaketakamichi 
最新版のマイグレーションファイルは`20201018154952_sample_09`だけど、ひとつ前のファイルにしか追加してない？👀

2020-10-19 04:49 UTC, merged